<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="CNDWVP022080077"><DocLocation><![CDATA[C:\workspace\BGRegression\src\bg\framework\app\functional\util\qtpScripts\SO Creation]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[SO Creation]]></DName>
<Res><![CDATA[Res26]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<AdditionalInfo>
<AdditionalDataName><![CDATA[Web Services Run Toolkit]]></AdditionalDataName>
<AdditionalDataValue><![CDATA[.NET Framework 2.0 WSE 3.0]]></AdditionalDataValue>
</AdditionalInfo>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[01/10/2013 - 10:44:32]]></Time>
<TimeTick>1380620672</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\SAP\FrontEnd\SAPgui\saplogon.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\SAP\FrontEnd\SAPgui\saplogon.exe",1]]></Details>
<Time><![CDATA[01/10/2013 - 10:44:32]]></Time>
<TimeTick>1380620672</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="11" status="Passed" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Run "C:\Program Files\SAP\FrontEnd\SAPgui\saplogon.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="10" status="Passed" Source="Action1" SourceLine="1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Permission denied<BR>Line (16): &quot;set txtfile = fso.OpenTextFile (SOFileLocation,2,true)&quot;. ]]></Details>
<Time><![CDATA[01/10/2013 - 10:44:34]]></Time>
<TimeTick>1380620674</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Failed" Source="Action1" SourceLine="15" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Permission denied<BR>Line (25): &quot;set txtfile1 = fso.OpenTextFile (&quot;C:\workspace\BGRegression\src\resources\bgmo_oab\booking\ServiceOrderNumber.txt&quot;,2,true)&quot;. ]]></Details>
<Time><![CDATA[01/10/2013 - 10:45:17]]></Time>
<TimeTick>1380620717</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="13" status="Failed" Source="Action1" SourceLine="24" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[01/10/2013 - 10:45:20]]></Time>
<TimeTick>1380620720</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[01/10/2013 - 10:45:20]]></Time>
<TimeTick>1380620720</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA["OKCode":Set "/ncic0"]]></Obj>
<Details plainTxt="False" ><![CDATA[Set "/ncic0"]]></Details>
<Time><![CDATA[01/10/2013 - 10:45:20]]></Time>
<TimeTick>1380620720</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" Source="Action1" SourceLine="35" >
<Disp><![CDATA["OKCode":Set "/ncic0"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[SendKey ENTER]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey ENTER]]></Details>
<Time><![CDATA[01/10/2013 - 10:45:20]]></Time>
<TimeTick>1380620720</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="19" Source="Action1" SourceLine="36" >
<Disp><![CDATA[SendKey ENTER]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Cont. Acct]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "Cont. Acct" object's parent "Session" (class SAPGuiSession). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[01/10/2013 - 10:45:39]]></Time>
<TimeTick>1380620739</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = ses[0]<br>miccommentproperty = <br>Mercury Class = SAPGuiSession<br>Index = 0<br>SapGui numeric component type = 12<br>]]></Details>
<Time><![CDATA[01/10/2013 - 10:45:39]]></Time>
<TimeTick>1380620739</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="22" status="Warning" nType="Parent description" Source="Action1" SourceLine="37" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="21" status="Failed" nType="Run Error" Source="Action1" SourceLine="37" >
<Disp><![CDATA[Cont. Acct]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="16" status="Failed" Source="Action1" SourceLine="35" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="15" status="Failed" Source="Action1" SourceLine="35" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;Cont. Acct&quot; object's parent &quot;Session&quot; (class SAPGuiSession). Verify that parent properties match an object currently displayed in your application.<BR>Line (38): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SAPGuiEdit(&quot;Cont. Acct&quot;).Set ContractAccNo&quot;. ]]></Details>
<Time><![CDATA[01/10/2013 - 10:45:39]]></Time>
<TimeTick>1380620739</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="23" status="Failed" Source="Action1" SourceLine="37" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[01/10/2013 - 10:45:50]]></Time>
<TimeTick>1380620750</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[01/10/2013 - 10:45:50]]></Time>
<TimeTick>1380620750</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Cont. Acct]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "Cont. Acct" object's parent "Session" (class SAPGuiSession). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[01/10/2013 - 10:45:50]]></Time>
<TimeTick>1380620750</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = ses[0]<br>miccommentproperty = <br>Mercury Class = SAPGuiSession<br>Index = 0<br>SapGui numeric component type = 12<br>]]></Details>
<Time><![CDATA[01/10/2013 - 10:45:50]]></Time>
<TimeTick>1380620750</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="28" status="Warning" nType="Parent description" Source="Action1" SourceLine="37" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="27" status="Failed" nType="Run Error" Source="Action1" SourceLine="37" >
<Disp><![CDATA[Cont. Acct]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="26" status="Failed" Source="Action1" SourceLine="37" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="25" status="Failed" Source="Action1" SourceLine="37" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;Cont. Acct&quot; object's parent &quot;Session&quot; (class SAPGuiSession). Verify that parent properties match an object currently displayed in your application.<BR>Line (39): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SAPGuiEdit(&quot;Cont. Acct&quot;).SetFocus&quot;. ]]></Details>
<Time><![CDATA[01/10/2013 - 10:45:50]]></Time>
<TimeTick>1380620750</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="29" status="Failed" Source="Action1" SourceLine="38" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:00]]></Time>
<TimeTick>1380620760</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:00]]></Time>
<TimeTick>1380620760</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Find Partner]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "Find Partner" object's parent "Session" (class SAPGuiSession). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:00]]></Time>
<TimeTick>1380620760</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = ses[0]<br>miccommentproperty = <br>Mercury Class = SAPGuiSession<br>Index = 0<br>SapGui numeric component type = 12<br>]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:00]]></Time>
<TimeTick>1380620760</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="34" status="Warning" nType="Parent description" Source="Action1" SourceLine="38" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="33" status="Failed" nType="Run Error" Source="Action1" SourceLine="38" >
<Disp><![CDATA[Find Partner]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="32" status="Failed" Source="Action1" SourceLine="38" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="31" status="Failed" Source="Action1" SourceLine="38" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;Find Partner&quot; object's parent &quot;Session&quot; (class SAPGuiSession). Verify that parent properties match an object currently displayed in your application.<BR>Line (40): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SAPGuiButton(&quot;Find Partner&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:00]]></Time>
<TimeTick>1380620760</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="35" status="Failed" Source="Action1" SourceLine="39" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:11]]></Time>
<TimeTick>1380620771</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:11]]></Time>
<TimeTick>1380620771</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Confirm Partner]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "Confirm Partner" object's parent "Session" (class SAPGuiSession). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:11]]></Time>
<TimeTick>1380620771</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = ses[0]<br>miccommentproperty = <br>Mercury Class = SAPGuiSession<br>Index = 0<br>SapGui numeric component type = 12<br>]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:11]]></Time>
<TimeTick>1380620771</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="40" status="Warning" nType="Parent description" Source="Action1" SourceLine="39" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="39" status="Failed" nType="Run Error" Source="Action1" SourceLine="39" >
<Disp><![CDATA[Confirm Partner]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="38" status="Failed" Source="Action1" SourceLine="39" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="37" status="Failed" Source="Action1" SourceLine="39" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;Confirm Partner&quot; object's parent &quot;Session&quot; (class SAPGuiSession). Verify that parent properties match an object currently displayed in your application.<BR>Line (41): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SAPGuiButton(&quot;Confirm Partner&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:11]]></Time>
<TimeTick>1380620771</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="41" status="Failed" Source="Action1" SourceLine="40" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:21]]></Time>
<TimeTick>1380620781</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:21]]></Time>
<TimeTick>1380620781</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[ToolBarControl]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "ToolBarControl" object's parent "Session" (class SAPGuiSession). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:21]]></Time>
<TimeTick>1380620781</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = ses[0]<br>miccommentproperty = <br>Mercury Class = SAPGuiSession<br>Index = 0<br>SapGui numeric component type = 12<br>]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:21]]></Time>
<TimeTick>1380620781</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="46" status="Warning" nType="Parent description" Source="Action1" SourceLine="40" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="45" status="Failed" nType="Run Error" Source="Action1" SourceLine="40" >
<Disp><![CDATA[ToolBarControl]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="44" status="Failed" Source="Action1" SourceLine="40" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="43" status="Failed" Source="Action1" SourceLine="40" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;ToolBarControl&quot; object's parent &quot;Session&quot; (class SAPGuiSession). Verify that parent properties match an object currently displayed in your application.<BR>Line (43): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SAPGuiToolbar(&quot;ToolBarControl&quot;).PressContextButton &quot;%_L1&quot;&quot;. ]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:22]]></Time>
<TimeTick>1380620782</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="47" status="Failed" Source="Action1" SourceLine="42" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:32]]></Time>
<TimeTick>1380620792</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:32]]></Time>
<TimeTick>1380620792</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[ToolBarControl]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "ToolBarControl" object's parent "Session" (class SAPGuiSession). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:32]]></Time>
<TimeTick>1380620792</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = ses[0]<br>miccommentproperty = <br>Mercury Class = SAPGuiSession<br>Index = 0<br>SapGui numeric component type = 12<br>]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:32]]></Time>
<TimeTick>1380620792</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="52" status="Warning" nType="Parent description" Source="Action1" SourceLine="42" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="51" status="Failed" nType="Run Error" Source="Action1" SourceLine="42" >
<Disp><![CDATA[ToolBarControl]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="50" status="Failed" Source="Action1" SourceLine="42" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="49" status="Failed" Source="Action1" SourceLine="42" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;ToolBarControl&quot; object's parent &quot;Session&quot; (class SAPGuiSession). Verify that parent properties match an object currently displayed in your application.<BR>Line (44): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SAPGuiToolbar(&quot;ToolBarControl&quot;).SelectMenuItem &quot;Customer Overview (OP)&quot;&quot;. ]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:32]]></Time>
<TimeTick>1380620792</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="53" status="Failed" Source="Action1" SourceLine="43" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:43]]></Time>
<TimeTick>1380620803</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:43]]></Time>
<TimeTick>1380620803</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[CoCode]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "CoCode" object's parent "Session" (class SAPGuiSession). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:43]]></Time>
<TimeTick>1380620803</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = ses[0]<br>miccommentproperty = <br>Mercury Class = SAPGuiSession<br>Index = 0<br>SapGui numeric component type = 12<br>]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:43]]></Time>
<TimeTick>1380620803</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="58" status="Warning" nType="Parent description" Source="Action1" SourceLine="43" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="57" status="Failed" nType="Run Error" Source="Action1" SourceLine="43" >
<Disp><![CDATA[CoCode]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="56" status="Failed" Source="Action1" SourceLine="43" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="55" status="Failed" Source="Action1" SourceLine="43" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;CoCode&quot; object's parent &quot;Session&quot; (class SAPGuiSession). Verify that parent properties match an object currently displayed in your application.<BR>Line (46): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SAPGuiEdit(&quot;CoCode&quot;).SetFocus&quot;. ]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:43]]></Time>
<TimeTick>1380620803</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="59" status="Failed" Source="Action1" SourceLine="45" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:54]]></Time>
<TimeTick>1380620814</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:54]]></Time>
<TimeTick>1380620814</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[CoCode]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "CoCode" object's parent "Session" (class SAPGuiSession). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:54]]></Time>
<TimeTick>1380620814</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = ses[0]<br>miccommentproperty = <br>Mercury Class = SAPGuiSession<br>Index = 0<br>SapGui numeric component type = 12<br>]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:54]]></Time>
<TimeTick>1380620814</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="64" status="Warning" nType="Parent description" Source="Action1" SourceLine="45" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="63" status="Failed" nType="Run Error" Source="Action1" SourceLine="45" >
<Disp><![CDATA[CoCode]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="62" status="Failed" Source="Action1" SourceLine="45" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="61" status="Failed" Source="Action1" SourceLine="45" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;CoCode&quot; object's parent &quot;Session&quot; (class SAPGuiSession). Verify that parent properties match an object currently displayed in your application.<BR>Line (47): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SAPGuiEdit(&quot;CoCode&quot;).SetCaretPos 1&quot;. ]]></Details>
<Time><![CDATA[01/10/2013 - 10:46:54]]></Time>
<TimeTick>1380620814</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="65" status="Failed" Source="Action1" SourceLine="46" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[01/10/2013 - 10:47:04]]></Time>
<TimeTick>1380620824</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[01/10/2013 - 10:47:04]]></Time>
<TimeTick>1380620824</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "GuiWindow" object's parent "Session" (class SAPGuiSession). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[01/10/2013 - 10:47:04]]></Time>
<TimeTick>1380620824</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = ses[0]<br>miccommentproperty = <br>Mercury Class = SAPGuiSession<br>Index = 0<br>SapGui numeric component type = 12<br>]]></Details>
<Time><![CDATA[01/10/2013 - 10:47:04]]></Time>
<TimeTick>1380620824</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="70" status="Warning" nType="Parent description" Source="Action1" SourceLine="46" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="69" status="Failed" nType="Run Error" Source="Action1" SourceLine="46" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="68" status="Failed" Source="Action1" SourceLine="46" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="67" status="Failed" Source="Action1" SourceLine="46" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;GuiWindow&quot; object's parent &quot;Session&quot; (class SAPGuiSession). Verify that parent properties match an object currently displayed in your application.<BR>Line (48): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SendKey F2&quot;. ]]></Details>
<Time><![CDATA[01/10/2013 - 10:47:04]]></Time>
<TimeTick>1380620824</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="71" status="Failed" Source="Action1" SourceLine="47" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[01/10/2013 - 10:47:17]]></Time>