<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="CNDWVP017060070"><DocLocation><![CDATA[C:\Documents and Settings\mathuric\Desktop\workspace\BGRegression\src\bg\framework\app\functional\util\qtpScripts\SO Creation]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[SO Creation]]></DName>
<Res><![CDATA[Res12]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<AdditionalInfo>
<AdditionalDataName><![CDATA[Web Services Run Toolkit]]></AdditionalDataName>
<AdditionalDataValue><![CDATA[.NET Framework 2.0 WSE 3.0]]></AdditionalDataValue>
</AdditionalInfo>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13/08/2013 - 09:58:26]]></Time>
<TimeTick>1376384306</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\SAP\FrontEnd\SAPgui\saplogon.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\SAP\FrontEnd\SAPgui\saplogon.exe",1]]></Details>
<Time><![CDATA[13/08/2013 - 09:58:26]]></Time>
<TimeTick>1376384306</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="11" status="Passed" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Run "C:\Program Files\SAP\FrontEnd\SAPgui\saplogon.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="10" status="Passed" Source="Action1" SourceLine="1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[13/08/2013 - 09:58:37]]></Time>
<TimeTick>1376384317</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[13/08/2013 - 09:58:37]]></Time>
<TimeTick>1376384317</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA["OKCode":Set "/ncic0"]]></Obj>
<Details plainTxt="False" ><![CDATA[Set "/ncic0"]]></Details>
<Time><![CDATA[13/08/2013 - 09:58:37]]></Time>
<TimeTick>1376384317</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" Source="Action1" SourceLine="72" >
<Disp><![CDATA["OKCode":Set "/ncic0"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[SendKey ENTER]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey ENTER]]></Details>
<Time><![CDATA[13/08/2013 - 09:58:37]]></Time>
<TimeTick>1376384317</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="17" Source="Action1" SourceLine="73" >
<Disp><![CDATA[SendKey ENTER]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA["Cont. Acct":Set "850026959363"]]></Obj>
<Details plainTxt="False" ><![CDATA[Set "850026959363"]]></Details>
<Time><![CDATA[13/08/2013 - 09:58:52]]></Time>
<TimeTick>1376384332</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" Source="Action1" SourceLine="75" >
<Disp><![CDATA["Cont. Acct":Set "850026959363"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA["Cont. Acct":SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[SetFocus]]></Details>
<Time><![CDATA[13/08/2013 - 09:58:52]]></Time>
<TimeTick>1376384332</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" Source="Action1" SourceLine="76" >
<Disp><![CDATA["Cont. Acct":SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA["Find Partner":Click]]></Obj>
<Details plainTxt="False" ><![CDATA[Click]]></Details>
<Time><![CDATA[13/08/2013 - 09:58:52]]></Time>
<TimeTick>1376384332</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="23" Source="Action1" SourceLine="77" >
<Disp><![CDATA["Find Partner":Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA["Confirm Partner":Click]]></Obj>
<Details plainTxt="False" ><![CDATA[Click]]></Details>
<Time><![CDATA[13/08/2013 - 09:58:54]]></Time>
<TimeTick>1376384334</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="25" Source="Action1" SourceLine="78" >
<Disp><![CDATA["Confirm Partner":Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA["TableTreeControl":ActivateNode "RegExp:=Partner .*;RegExp:=Premise .*;RegExp:=Contract Account 850026959363;RegExp:=Contract .*;RegExp:=Installation .* "]]></Obj>
<Details plainTxt="False" ><![CDATA[ActivateNode "RegExp:=Partner .*;RegExp:=Premise .*;RegExp:=Contract Account 850026959363;RegExp:=Contract .*;RegExp:=Installation .* "]]></Details>
<Time><![CDATA[13/08/2013 - 09:58:58]]></Time>
<TimeTick>1376384338</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="27" Source="Action1" SourceLine="84" >
<Disp><![CDATA["TableTreeControl":ActivateNode "RegExp:=Partner .*;RegExp:=Premise .*;RegExp:=Contract Account 850026959363;RegExp:=Contract .*;RegExp:=Installation .* "]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[TableTreeControl]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the specified item of the TableTreeControl object. Confirm that the specified item is included in the object's item collection.]]></Details>
<Time><![CDATA[13/08/2013 - 09:58:58]]></Time>
<TimeTick>1376384338</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[TableTreeControl]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = shell<br>Mercury Class = SAPGuiTree<br>SapGui numeric component type = 200<br>]]></Details>
<Time><![CDATA[13/08/2013 - 09:58:58]]></Time>
<TimeTick>1376384338</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="29" status="Warning" nType="Description" Source="Action1" SourceLine="84" >
<Disp><![CDATA[TableTreeControl]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="28" status="Failed" nType="Run Error" Source="Action1" SourceLine="84" >
<Disp><![CDATA[TableTreeControl]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="14" status="Failed" Source="Action1" SourceLine="72" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="13" status="Failed" Source="Action1" SourceLine="72" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the specified item of the TableTreeControl object. Confirm that the specified item is included in the object's item collection.<BR>Line (85): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SAPGuiTree(&quot;TableTreeControl&quot;).ActivateNode &quot;RegExp:=Partner .*;RegExp:=Premise .*;RegExp:=Contract Account &quot;&amp;ContractAccNo&amp;&quot;;RegExp:=Contract .*;RegExp:=Installation .* &quot;&quot;. ]]></Details>
<Time><![CDATA[13/08/2013 - 09:58:58]]></Time>
<TimeTick>1376384338</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="30" status="Failed" Source="Action1" SourceLine="84" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[13/08/2013 - 09:58:59]]></Time>
<TimeTick>1376384339</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[13/08/2013 - 09:58:59]]></Time>
<TimeTick>1376384339</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA["TableTreeControl":ActivateNode "RegExp:=Partner .*;RegExp:=Premise .*;RegExp:=Contract Account 850026959363;RegExp:=Contract ;RegExp:=Installation .* "]]></Obj>
<Details plainTxt="False" ><![CDATA[ActivateNode "RegExp:=Partner .*;RegExp:=Premise .*;RegExp:=Contract Account 850026959363;RegExp:=Contract ;RegExp:=Installation .* "]]></Details>
<Time><![CDATA[13/08/2013 - 09:58:59]]></Time>
<TimeTick>1376384339</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="34" Source="Action1" SourceLine="88" >
<Disp><![CDATA["TableTreeControl":ActivateNode "RegExp:=Partner .*;RegExp:=Premise .*;RegExp:=Contract Account 850026959363;RegExp:=Contract ;RegExp:=Installation .* "]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[TableTreeControl]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the specified item of the TableTreeControl object. Confirm that the specified item is included in the object's item collection.]]></Details>
<Time><![CDATA[13/08/2013 - 09:58:59]]></Time>
<TimeTick>1376384339</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[TableTreeControl]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = shell<br>Mercury Class = SAPGuiTree<br>SapGui numeric component type = 200<br>]]></Details>
<Time><![CDATA[13/08/2013 - 09:58:59]]></Time>
<TimeTick>1376384339</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="36" status="Warning" nType="Description" Source="Action1" SourceLine="88" >
<Disp><![CDATA[TableTreeControl]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="35" status="Failed" nType="Run Error" Source="Action1" SourceLine="88" >
<Disp><![CDATA[TableTreeControl]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="33" status="Failed" Source="Action1" SourceLine="88" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="32" status="Failed" Source="Action1" SourceLine="88" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the specified item of the TableTreeControl object. Confirm that the specified item is included in the object's item collection.<BR>Line (89): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SAPGuiTree(&quot;TableTreeControl&quot;).ActivateNode &quot;RegExp:=Partner .*;RegExp:=Premise .*;RegExp:=Contract Account &quot;&amp;ContractAccNo&amp;&quot;;RegExp:=Contract &quot;&amp;ContractNoVal&amp;&quot;;RegExp:=Installation .* &quot;&quot;. ]]></Details>
<Time><![CDATA[13/08/2013 - 09:58:59]]></Time>
<TimeTick>1376384339</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="37" status="Failed" Source="Action1" SourceLine="88" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:00]]></Time>
<TimeTick>1376384340</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:00]]></Time>
<TimeTick>1376384340</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[MPAN.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:00]]></Time>
<TimeTick>1376384340</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="41" Source="Action1" SourceLine="88" >
<Disp><![CDATA[MPAN.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[MPR.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:01]]></Time>
<TimeTick>1376384341</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="43" Source="Action1" SourceLine="97" >
<Disp><![CDATA[MPR.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Premise]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "Premise" (of class SAPGuiEdit). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:02]]></Time>
<TimeTick>1376384342</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Premise]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = EANLD-VSTELLE<br>Mercury Class = SAPGuiEdit<br>SapGui numeric component type = 32<br>]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:02]]></Time>
<TimeTick>1376384342</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="46" status="Warning" nType="Description" Source="Action1" SourceLine="104" >
<Disp><![CDATA[Premise]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="45" status="Failed" nType="Run Error" Source="Action1" SourceLine="104" >
<Disp><![CDATA[Premise]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="40" status="Failed" Source="Action1" SourceLine="88" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="39" status="Failed" Source="Action1" SourceLine="88" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Premise&quot; (of class SAPGuiEdit). Verify that this object's properties match an object currently displayed in your application.<BR>Line (105): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SAPGuiEdit(&quot;Premise&quot;).Output CheckPoint(&quot;Premise&quot;)&quot;. ]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:02]]></Time>
<TimeTick>1376384342</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="47" status="Failed" Source="Action1" SourceLine="104" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:03]]></Time>
<TimeTick>1376384343</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:03]]></Time>
<TimeTick>1376384343</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Premise]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "Premise" (of class SAPGuiEdit). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:03]]></Time>
<TimeTick>1376384343</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Premise]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = EANLD-VSTELLE<br>Mercury Class = SAPGuiEdit<br>SapGui numeric component type = 32<br>]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:03]]></Time>
<TimeTick>1376384343</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="52" status="Warning" nType="Description" Source="Action1" SourceLine="106" >
<Disp><![CDATA[Premise]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="51" status="Failed" nType="Run Error" Source="Action1" SourceLine="106" >
<Disp><![CDATA[Premise]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="50" status="Failed" Source="Action1" SourceLine="106" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="49" status="Failed" Source="Action1" SourceLine="106" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Premise&quot; (of class SAPGuiEdit). Verify that this object's properties match an object currently displayed in your application.<BR>Line (107): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SAPGuiEdit(&quot;Premise&quot;).SetFocus&quot;. ]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:03]]></Time>
<TimeTick>1376384343</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="53" status="Failed" Source="Action1" SourceLine="106" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:04]]></Time>
<TimeTick>1376384344</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:04]]></Time>
<TimeTick>1376384344</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[SendKey F2]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey F2]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:04]]></Time>
<TimeTick>1376384344</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="57" Source="Action1" SourceLine="106" >
<Disp><![CDATA[SendKey F2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[The parameter is incorrect.
]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:04]]></Time>
<TimeTick>1376384344</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>SapGui transaction = IW32<br>SapGui screen number = 101<br>SapGui program = SAPLCOIH<br>Name = wnd[0]<br>miccommentproperty = <br>Mercury Class = SAPGuiWindow<br>Index = 0<br>SapGui numeric component type = 21<br>]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:04]]></Time>
<TimeTick>1376384344</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="59" status="Warning" nType="Description" Source="Action1" SourceLine="106" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="58" status="Failed" nType="Run Error" Source="Action1" SourceLine="106" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="56" status="Failed" Source="Action1" SourceLine="106" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="55" status="Failed" Source="Action1" SourceLine="106" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The parameter is incorrect.<BR><BR>Line (108): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SendKey F2&quot;. ]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:04]]></Time>
<TimeTick>1376384344</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="60" status="Failed" Source="Action1" SourceLine="107" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:04]]></Time>
<TimeTick>1376384344</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:04]]></Time>
<TimeTick>1376384344</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA["StatusBar":Enter a contact class]]></Obj>
<Details plainTxt="False" ><![CDATA[Success]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:04]]></Time>
<TimeTick>1376384344</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="64" Source="Action1" SourceLine="107" >
<Disp><![CDATA["StatusBar":Enter a contact class]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Connection Obj.]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "Connection Obj." (of class SAPGuiEdit). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:04]]></Time>
<TimeTick>1376384344</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Connection Obj.]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = EVBSD-HAUS<br>Mercury Class = SAPGuiEdit<br>SapGui numeric component type = 32<br>]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:04]]></Time>
<TimeTick>1376384344</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="67" status="Warning" nType="Description" Source="Action1" SourceLine="109" >
<Disp><![CDATA[Connection Obj.]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="66" status="Failed" nType="Run Error" Source="Action1" SourceLine="109" >
<Disp><![CDATA[Connection Obj.]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="63" status="Failed" Source="Action1" SourceLine="107" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="62" status="Failed" Source="Action1" SourceLine="107" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Connection Obj.&quot; (of class SAPGuiEdit). Verify that this object's properties match an object currently displayed in your application.<BR>Line (110): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SAPGuiEdit(&quot;Connection Obj.&quot;).Output CheckPoint(&quot;Connection Obj.&quot;)&quot;. ]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:04]]></Time>
<TimeTick>1376384344</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="68" status="Failed" Source="Action1" SourceLine="109" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:05]]></Time>
<TimeTick>1376384345</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:05]]></Time>
<TimeTick>1376384345</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA["Back   (F3)":Click]]></Obj>
<Details plainTxt="False" ><![CDATA[Click]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:05]]></Time>
<TimeTick>1376384345</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="72" Source="Action1" SourceLine="111" >
<Disp><![CDATA["Back   (F3)":Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Devices]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "Devices" (of class SAPGuiButton). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:08]]></Time>
<TimeTick>1376384348</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Devices]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = EANLD-DEVSBUT<br>Mercury Class = SAPGuiButton<br>SapGui numeric component type = 40<br>]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:08]]></Time>
<TimeTick>1376384348</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="75" status="Warning" nType="Description" Source="Action1" SourceLine="112" >
<Disp><![CDATA[Devices]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="74" status="Failed" nType="Run Error" Source="Action1" SourceLine="112" >
<Disp><![CDATA[Devices]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="71" status="Failed" Source="Action1" SourceLine="111" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="70" status="Failed" Source="Action1" SourceLine="111" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Devices&quot; (of class SAPGuiButton). Verify that this object's properties match an object currently displayed in your application.<BR>Line (113): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SAPGuiButton(&quot;Devices&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:08]]></Time>
<TimeTick>1376384348</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="76" status="Failed" Source="Action1" SourceLine="112" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:14]]></Time>
<TimeTick>1376384354</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:14]]></Time>
<TimeTick>1376384354</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Device data]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "Device data" (of class SAPGuiTable). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:14]]></Time>
<TimeTick>1376384354</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Device data]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = SAPLEG70TC_DEVRATE_C<br>Mercury Class = SAPGuiTable<br>SapGui numeric component type = 80<br>]]></Details>
<Time><![CDATA[13/08/2013 - 09:59:14]]></Time>
<TimeTick>1376384354</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="81" status="Warning" nType="Description" Source="Action1" SourceLine="112" >
<Disp><![CDATA[Device data]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="13" nRep="80" status="Failed" nType="Run Error" Source="Action1" SourceLine="112" >
<Disp><![CDATA[Device data]]></Disp>
</NodeArgs>
</Step>