<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="QuickTest Professional" productVer="11.00" os="Windows 7" host="PC176102"><DocLocation><![CDATA[D:\karthi\TetrisProject\TetrisProject\Slingshot\src\bg\framework\app\functional\util\qtpScripts\SubmitMeterRead]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[SubmitMeterRead]]></DName>
<Res><![CDATA[Res60]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[11/22/2013 - 11:08:17]]></Time>
<TimeTick>1385098697</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[wndSAPEasyAccess]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[11/22/2013 - 11:08:17]]></Time>
<TimeTick>1385098697</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[wndSAPEasyAccess.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/22/2013 - 11:08:17]]></Time>
<TimeTick>1385098697</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="10" Source="Action1" SourceLine="33" >
<Disp><![CDATA[wndSAPEasyAccess.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[OKCode.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/22/2013 - 11:08:19]]></Time>
<TimeTick>1385098699</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="11" Source="Action1" SourceLine="58" >
<Disp><![CDATA[OKCode.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA["OKCode":Set "/n ECENV_BP"]]></Obj>
<Details plainTxt="False" ><![CDATA[Set "/n ECENV_BP"]]></Details>
<Time><![CDATA[11/22/2013 - 11:08:19]]></Time>
<TimeTick>1385098699</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="13" Source="Action1" SourceLine="37" >
<Disp><![CDATA["OKCode":Set "/n ECENV_BP"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[SendKey ENTER]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey ENTER]]></Details>
<Time><![CDATA[11/22/2013 - 11:08:19]]></Time>
<TimeTick>1385098699</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" Source="Action1" SourceLine="38" >
<Disp><![CDATA[SendKey ENTER]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="9" Source="Action1" SourceLine="33" >
<Disp><![CDATA[wndSAPEasyAccess]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[wndDataEnvironmentBusiness]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[11/22/2013 - 11:08:21]]></Time>
<TimeTick>1385098701</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[wndDataEnvironmentBusiness.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/22/2013 - 11:08:21]]></Time>
<TimeTick>1385098701</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="17" Source="Action1" SourceLine="58" >
<Disp><![CDATA[wndDataEnvironmentBusiness.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[edtBusiness Partner.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/22/2013 - 11:08:23]]></Time>
<TimeTick>1385098703</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" Source="Action1" SourceLine="58" >
<Disp><![CDATA[edtBusiness Partner.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA["edtBusiness Partner":Set "2002097499"]]></Obj>
<Details plainTxt="False" ><![CDATA[Set "2002097499"]]></Details>
<Time><![CDATA[11/22/2013 - 11:08:24]]></Time>
<TimeTick>1385098704</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" Source="Action1" SourceLine="41" >
<Disp><![CDATA["edtBusiness Partner":Set "2002097499"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[SendKey ENTER]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey ENTER]]></Details>
<Time><![CDATA[11/22/2013 - 11:08:24]]></Time>
<TimeTick>1385098704</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="22" Source="Action1" SourceLine="42" >
<Disp><![CDATA[SendKey ENTER]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="16" Source="Action1" SourceLine="58" >
<Disp><![CDATA[wndDataEnvironmentBusiness]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[wndDataEnvironment]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[11/22/2013 - 11:08:25]]></Time>
<TimeTick>1385098705</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[wndDataEnvironment.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/22/2013 - 11:08:25]]></Time>
<TimeTick>1385098705</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="24" Source="Action1" SourceLine="44" >
<Disp><![CDATA[wndDataEnvironment.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[wndDataEnvironment.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/22/2013 - 11:08:31]]></Time>
<TimeTick>1385098711</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="25" Source="Action1" SourceLine="180" >
<Disp><![CDATA[wndDataEnvironment.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[IS-U Installation]]></Obj>
<Details plainTxt="False" ><![CDATA[The "IS-U Installation" object's description matches more than one of the objects currently displayed in your application. Add additional properties to the object description in order to uniquely identify the object.]]></Details>
<Time><![CDATA[11/22/2013 - 11:08:32]]></Time>
<TimeTick>1385098712</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[IS-U Installation]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>SAP component ID relative to its parent window = wnd[0]/usr/lbl[16,8]<br>miccommentproperty = <br>Mercury Class = SAPGuiLabel<br>SapGui numeric component type = 30<br>content = IS-U Installation<br>]]></Details>
<Time><![CDATA[11/22/2013 - 11:08:32]]></Time>
<TimeTick>1385098712</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="28" status="Warning" nType="Description" Source="Action1" SourceLine="186" >
<Disp><![CDATA[IS-U Installation]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="27" status="Failed" nType="Run Error" Source="Action1" SourceLine="186" >
<Disp><![CDATA[IS-U Installation]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="23" status="Failed" Source="Action1" SourceLine="44" >
<Disp><![CDATA[wndDataEnvironment]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="8" status="Failed" Source="Action1" SourceLine="33" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;IS-U Installation&quot; object's description matches more than one of the objects currently displayed in your application. Add additional properties to the object description in order to uniquely identify the object.<BR>Line (187): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;wndDataEnvironment&quot;).SAPGuiLabel(&quot;IS-U Installation&quot;).SetFocus&quot;. ]]></Details>
<Time><![CDATA[11/22/2013 - 11:08:32]]></Time>
<TimeTick>1385098712</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="29" status="Failed" Source="Action1" SourceLine="186" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[11/22/2013 - 11:08:45]]></Time>
<TimeTick>1385098725</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[wndDataEnvironment]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[11/22/2013 - 11:08:45]]></Time>
<TimeTick>1385098725</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[SendKey F2]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey F2]]></Details>
<Time><![CDATA[11/22/2013 - 11:08:45]]></Time>
<TimeTick>1385098725</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="33" Source="Action1" SourceLine="186" >
<Disp><![CDATA[SendKey F2]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="32" Source="Action1" SourceLine="186" >
<Disp><![CDATA[wndDataEnvironment]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[wndDisplayInstallation]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[11/22/2013 - 11:08:59]]></Time>
<TimeTick>1385098739</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[wndDisplayInstallation.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/22/2013 - 11:08:59]]></Time>
<TimeTick>1385098739</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="36" Source="Action1" SourceLine="58" >
<Disp><![CDATA[wndDisplayInstallation.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[wndDisplayInstallation.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/22/2013 - 11:09:01]]></Time>
<TimeTick>1385098741</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="38" Source="Action1" SourceLine="58" >
<Disp><![CDATA[wndDisplayInstallation.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[wndDisplayInstallation.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/22/2013 - 11:09:03]]></Time>
<TimeTick>1385098743</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="40" Source="Action1" SourceLine="58" >
<Disp><![CDATA[wndDisplayInstallation.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[wndDisplayInstallation.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/22/2013 - 11:09:05]]></Time>
<TimeTick>1385098745</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="42" Source="Action1" SourceLine="58" >
<Disp><![CDATA[wndDisplayInstallation.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[wndDisplayInstallation.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/22/2013 - 11:09:07]]></Time>
<TimeTick>1385098747</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="44" Source="Action1" SourceLine="58" >
<Disp><![CDATA[wndDisplayInstallation.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[wndDisplayInstallation.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/22/2013 - 11:09:10]]></Time>
<TimeTick>1385098750</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="46" Source="Action1" SourceLine="58" >
<Disp><![CDATA[wndDisplayInstallation.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[wndDisplayInstallation.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/22/2013 - 11:09:12]]></Time>
<TimeTick>1385098752</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="48" Source="Action1" SourceLine="58" >
<Disp><![CDATA[wndDisplayInstallation.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[wndDisplayInstallation.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/22/2013 - 11:09:14]]></Time>
<TimeTick>1385098754</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="50" Source="Action1" SourceLine="58" >
<Disp><![CDATA[wndDisplayInstallation.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[wndDisplayInstallation.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/22/2013 - 11:09:16]]></Time>
<TimeTick>1385098756</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="52" Source="Action1" SourceLine="58" >
<Disp><![CDATA[wndDisplayInstallation.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[wndDisplayInstallation.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/22/2013 - 11:09:18]]></Time>
<TimeTick>1385098758</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="54" Source="Action1" SourceLine="58" >
<Disp><![CDATA[wndDisplayInstallation.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[btnBillingPeriods]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "btnBillingPeriods" object's parent "wndDisplayInstallation" (class SAPGuiWindow). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[11/22/2013 - 11:09:18]]></Time>
<TimeTick>1385098758</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[wndDisplayInstallation]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>SapGui transaction = ECENV_BP<br>SapGui screen number = 201<br>SapGui program = SAPLES30<br>Name = wnd[0]<br>Mercury Class = SAPGuiWindow<br>SapGui numeric component type = 21<br>]]></Details>
<Time><![CDATA[11/22/2013 - 11:09:18]]></Time>
<TimeTick>1385098758</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="57" status="Warning" nType="Parent description" Source="Action1" SourceLine="189" >
<Disp><![CDATA[wndDisplayInstallation]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="56" status="Failed" nType="Run Error" Source="Action1" SourceLine="189" >
<Disp><![CDATA[btnBillingPeriods]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="35" status="Failed" Source="Action1" SourceLine="58" >
<Disp><![CDATA[wndDisplayInstallation]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="31" status="Failed" Source="Action1" SourceLine="186" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;btnBillingPeriods&quot; object's parent &quot;wndDisplayInstallation&quot; (class SAPGuiWindow). Verify that parent properties match an object currently displayed in your application.<BR>Line (190): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;wndDisplayInstallation&quot;).SAPGuiButton(&quot;btnBillingPeriods&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[11/22/2013 - 11:09:18]]></Time>
<TimeTick>1385098758</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="58" status="Failed" Source="Action1" SourceLine="189" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[11/22/2013 - 11:09:22]]></Time>
<TimeTick>1385098762</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[wndBillingViewofInstallation]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[11/22/2013 - 11:09:22]]></Time>
<TimeTick>1385098762</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[wndBillingViewofInstallation.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/22/2013 - 11:09:22]]></Time>
<TimeTick>1385098762</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="62" Source="Action1" SourceLine="189" >
<Disp><![CDATA[wndBillingViewofInstallation.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="61" Source="Action1" SourceLine="189" >
<Disp><![CDATA[wndBillingViewofInstallation]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="60" Source="Action1" SourceLine="189" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/22/2013 - 11:08:06" eTime="11/22/2013 - 11:09:33" passed="0" failed="4" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[SubmitMeterRead Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="11/22/2013 - 11:08:04" eTime="11/22/2013 - 11:09:33" passed="0" failed="4" warnings="2" ><Param ><ParamName><![CDATA[BpOrgNumber]]></ParamName><ParamVal><![CDATA[]]></ParamVal>
</Param>
<Param ><ParamName><![CDATA[Accountnumber]]></ParamName><ParamVal><![CDATA[]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test SubmitMeterRead Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>