<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="CNDWVP017060070"><DocLocation><![CDATA[C:\workspace\BGRegression\src\bg\framework\app\functional\util\qtpScripts\SO Creation]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[SO Creation]]></DName>
<Res><![CDATA[Res28]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<AdditionalInfo>
<AdditionalDataName><![CDATA[Web Services Run Toolkit]]></AdditionalDataName>
<AdditionalDataValue><![CDATA[.NET Framework 2.0 WSE 3.0]]></AdditionalDataValue>
</AdditionalInfo>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:27]]></Time>
<TimeTick>1380636387</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\SAP\FrontEnd\SAPgui\saplogon.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\SAP\FrontEnd\SAPgui\saplogon.exe",1]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:27]]></Time>
<TimeTick>1380636387</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="11" status="Passed" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Run "C:\Program Files\SAP\FrontEnd\SAPgui\saplogon.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="10" status="Passed" Source="Action1" SourceLine="1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:38]]></Time>
<TimeTick>1380636398</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:38]]></Time>
<TimeTick>1380636398</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA["OKCode":Set "/ncic0"]]></Obj>
<Details plainTxt="False" ><![CDATA[Set "/ncic0"]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:38]]></Time>
<TimeTick>1380636398</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" Source="Action1" SourceLine="35" >
<Disp><![CDATA["OKCode":Set "/ncic0"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[SendKey ENTER]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey ENTER]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:38]]></Time>
<TimeTick>1380636398</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="17" Source="Action1" SourceLine="36" >
<Disp><![CDATA[SendKey ENTER]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA["Cont. Acct":Set ""]]></Obj>
<Details plainTxt="False" ><![CDATA[Set ""]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:41]]></Time>
<TimeTick>1380636401</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" Source="Action1" SourceLine="37" >
<Disp><![CDATA["Cont. Acct":Set ""]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA["Cont. Acct":SetFocus]]></Obj>
<Details plainTxt="False" ><![CDATA[SetFocus]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:41]]></Time>
<TimeTick>1380636401</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" Source="Action1" SourceLine="38" >
<Disp><![CDATA["Cont. Acct":SetFocus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA["Find Partner":Click]]></Obj>
<Details plainTxt="False" ><![CDATA[Click]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:41]]></Time>
<TimeTick>1380636401</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="23" Source="Action1" SourceLine="39" >
<Disp><![CDATA["Find Partner":Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA["Confirm Partner":Click]]></Obj>
<Details plainTxt="False" ><![CDATA[Click]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:47]]></Time>
<TimeTick>1380636407</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="25" Source="Action1" SourceLine="40" >
<Disp><![CDATA["Confirm Partner":Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Confirm Partner]]></Obj>
<Details plainTxt="False" ><![CDATA[The operation cannot be performed]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:47]]></Time>
<TimeTick>1380636407</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Confirm Partner]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = 742C<br>Mercury Class = SAPGuiButton<br>SapGui numeric component type = 40<br>]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:47]]></Time>
<TimeTick>1380636407</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="27" status="Warning" nType="Description" Source="Action1" SourceLine="40" >
<Disp><![CDATA[Confirm Partner]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="26" status="Failed" nType="Run Error" Source="Action1" SourceLine="40" >
<Disp><![CDATA[Confirm Partner]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="14" status="Failed" Source="Action1" SourceLine="35" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="13" status="Failed" Source="Action1" SourceLine="35" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The operation cannot be performed<BR>Line (41): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SAPGuiButton(&quot;Confirm Partner&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:47]]></Time>
<TimeTick>1380636407</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="28" status="Failed" Source="Action1" SourceLine="40" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:47]]></Time>
<TimeTick>1380636407</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:47]]></Time>
<TimeTick>1380636407</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[ToolBarControl]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "ToolBarControl" (of class SAPGuiToolbar). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:47]]></Time>
<TimeTick>1380636407</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[ToolBarControl]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = shell<br>SapGui numeric component type = 202<br>]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:47]]></Time>
<TimeTick>1380636407</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="33" status="Warning" nType="Description" Source="Action1" SourceLine="40" >
<Disp><![CDATA[ToolBarControl]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="32" status="Failed" nType="Run Error" Source="Action1" SourceLine="40" >
<Disp><![CDATA[ToolBarControl]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="31" status="Failed" Source="Action1" SourceLine="40" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="30" status="Failed" Source="Action1" SourceLine="40" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;ToolBarControl&quot; (of class SAPGuiToolbar). Verify that this object's properties match an object currently displayed in your application.<BR>Line (43): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SAPGuiToolbar(&quot;ToolBarControl&quot;).PressContextButton &quot;%_L1&quot;&quot;. ]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:47]]></Time>
<TimeTick>1380636407</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="34" status="Failed" Source="Action1" SourceLine="42" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:47]]></Time>
<TimeTick>1380636407</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:47]]></Time>
<TimeTick>1380636407</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[ToolBarControl]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "ToolBarControl" (of class SAPGuiToolbar). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:47]]></Time>
<TimeTick>1380636407</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[ToolBarControl]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = shell<br>SapGui numeric component type = 202<br>]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:47]]></Time>
<TimeTick>1380636407</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="39" status="Warning" nType="Description" Source="Action1" SourceLine="42" >
<Disp><![CDATA[ToolBarControl]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="38" status="Failed" nType="Run Error" Source="Action1" SourceLine="42" >
<Disp><![CDATA[ToolBarControl]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="37" status="Failed" Source="Action1" SourceLine="42" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="36" status="Failed" Source="Action1" SourceLine="42" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;ToolBarControl&quot; (of class SAPGuiToolbar). Verify that this object's properties match an object currently displayed in your application.<BR>Line (44): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SAPGuiToolbar(&quot;ToolBarControl&quot;).SelectMenuItem &quot;Customer Overview (OP)&quot;&quot;. ]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:47]]></Time>
<TimeTick>1380636407</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="40" status="Failed" Source="Action1" SourceLine="43" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:48]]></Time>
<TimeTick>1380636408</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:48]]></Time>
<TimeTick>1380636408</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[CoCode]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "CoCode" (of class SAPGuiEdit). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:48]]></Time>
<TimeTick>1380636408</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[CoCode]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Type = GuiCTextField<br>Name = EVER-BUKRS<br>miccommentproperty = <br>Mercury Class = SAPGuiEdit<br>SapGui numeric component type = 32<br>attachedtext = CoCode<br>]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:48]]></Time>
<TimeTick>1380636408</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="45" status="Warning" nType="Description" Source="Action1" SourceLine="43" >
<Disp><![CDATA[CoCode]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="44" status="Failed" nType="Run Error" Source="Action1" SourceLine="43" >
<Disp><![CDATA[CoCode]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="43" status="Failed" Source="Action1" SourceLine="43" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="42" status="Failed" Source="Action1" SourceLine="43" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;CoCode&quot; (of class SAPGuiEdit). Verify that this object's properties match an object currently displayed in your application.<BR>Line (46): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SAPGuiEdit(&quot;CoCode&quot;).SetFocus&quot;. ]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:48]]></Time>
<TimeTick>1380636408</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="46" status="Failed" Source="Action1" SourceLine="45" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:48]]></Time>
<TimeTick>1380636408</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:48]]></Time>
<TimeTick>1380636408</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[CoCode]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "CoCode" (of class SAPGuiEdit). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:48]]></Time>
<TimeTick>1380636408</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[CoCode]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Type = GuiCTextField<br>Name = EVER-BUKRS<br>miccommentproperty = <br>Mercury Class = SAPGuiEdit<br>SapGui numeric component type = 32<br>attachedtext = CoCode<br>]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:48]]></Time>
<TimeTick>1380636408</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="51" status="Warning" nType="Description" Source="Action1" SourceLine="45" >
<Disp><![CDATA[CoCode]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="50" status="Failed" nType="Run Error" Source="Action1" SourceLine="45" >
<Disp><![CDATA[CoCode]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="49" status="Failed" Source="Action1" SourceLine="45" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="48" status="Failed" Source="Action1" SourceLine="45" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;CoCode&quot; (of class SAPGuiEdit). Verify that this object's properties match an object currently displayed in your application.<BR>Line (47): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SAPGuiEdit(&quot;CoCode&quot;).SetCaretPos 1&quot;. ]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:48]]></Time>
<TimeTick>1380636408</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="52" status="Failed" Source="Action1" SourceLine="46" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:48]]></Time>
<TimeTick>1380636408</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:48]]></Time>
<TimeTick>1380636408</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[SendKey F2]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey F2]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:48]]></Time>
<TimeTick>1380636408</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="56" Source="Action1" SourceLine="46" >
<Disp><![CDATA[SendKey F2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[The operation cannot be performed]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:48]]></Time>
<TimeTick>1380636408</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>SapGui transaction = IW32<br>SapGui screen number = 101<br>SapGui program = SAPLCOIH<br>Name = wnd[0]<br>miccommentproperty = <br>Mercury Class = SAPGuiWindow<br>Index = 0<br>SapGui numeric component type = 21<br>]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:48]]></Time>
<TimeTick>1380636408</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="58" status="Warning" nType="Description" Source="Action1" SourceLine="46" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="57" status="Failed" nType="Run Error" Source="Action1" SourceLine="46" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="55" status="Failed" Source="Action1" SourceLine="46" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="54" status="Failed" Source="Action1" SourceLine="46" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The operation cannot be performed<BR>Line (48): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SendKey F2&quot;. ]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:48]]></Time>
<TimeTick>1380636408</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="59" status="Failed" Source="Action1" SourceLine="47" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:49]]></Time>
<TimeTick>1380636409</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:49]]></Time>
<TimeTick>1380636409</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Contract number]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "Contract number" (of class SAPGuiEdit). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:49]]></Time>
<TimeTick>1380636409</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Contract number]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = EVERD-VERTRAG<br>Mercury Class = SAPGuiEdit<br>SapGui numeric component type = 32<br>]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:49]]></Time>
<TimeTick>1380636409</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="64" status="Warning" nType="Description" Source="Action1" SourceLine="47" >
<Disp><![CDATA[Contract number]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="63" status="Failed" nType="Run Error" Source="Action1" SourceLine="47" >
<Disp><![CDATA[Contract number]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="62" status="Failed" Source="Action1" SourceLine="47" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="61" status="Failed" Source="Action1" SourceLine="47" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Contract number&quot; (of class SAPGuiEdit). Verify that this object's properties match an object currently displayed in your application.<BR>Line (49): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SAPGuiEdit(&quot;Contract number&quot;).Output CheckPoint(&quot;Contract number&quot;)&quot;. ]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:49]]></Time>
<TimeTick>1380636409</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="65" status="Failed" Source="Action1" SourceLine="48" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:49]]></Time>
<TimeTick>1380636409</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:49]]></Time>
<TimeTick>1380636409</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA["Back   (F3)":Click]]></Obj>
<Details plainTxt="False" ><![CDATA[Click]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:49]]></Time>
<TimeTick>1380636409</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="69" Source="Action1" SourceLine="48" >
<Disp><![CDATA["Back   (F3)":Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Back   (F3)]]></Obj>
<Details plainTxt="False" ><![CDATA[The operation cannot be performed]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:49]]></Time>
<TimeTick>1380636409</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Back   (F3)]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = btn[3]<br>Mercury Class = SAPGuiButton<br>SapGui numeric component type = 40<br>]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:49]]></Time>
<TimeTick>1380636409</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="71" status="Warning" nType="Description" Source="Action1" SourceLine="48" >
<Disp><![CDATA[Back   (F3)]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="70" status="Failed" nType="Run Error" Source="Action1" SourceLine="48" >
<Disp><![CDATA[Back   (F3)]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="68" status="Failed" Source="Action1" SourceLine="48" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="67" status="Failed" Source="Action1" SourceLine="48" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The operation cannot be performed<BR>Line (50): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;GuiWindow&quot;).SAPGuiButton(&quot;Back   (F3)&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:49]]></Time>
<TimeTick>1380636409</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="72" status="Failed" Source="Action1" SourceLine="49" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:49]]></Time>
<TimeTick>1380636409</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[GuiWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:49]]></Time>
<TimeTick>1380636409</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[TABSTRIP101]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "TABSTRIP101" (of class SAPGuiTabStrip). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:49]]></Time>
<TimeTick>1380636409</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[TABSTRIP101]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = TABSTRIP101<br>Mercury Class = SAPGuiTabStrip<br>SapGui numeric component type = 90<br>]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:49]]></Time>
<TimeTick>1380636409</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="77" status="Warning" nType="Description" Source="Action1" SourceLine="49" >
<Disp><![CDATA[TABSTRIP101]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="12" nRep="76" status="Failed" nType="Run Error" Source="Action1" SourceLine="49" >
<Disp><![CDATA[TABSTRIP101]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[01/10/2013 - 15:06:49]]></Time>
<TimeTick>1380636409</TimeTick>
<NodeArgs eType="General" icon="13" nRep="78" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="75" status="Failed" Source="Action1" SourceLine="49" >
<Disp><![CDATA[GuiWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="74" status="Failed" Source="Action1" SourceLine="49" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="01/10/2013 - 15:06:16" eTime="01/10/2013 - 15:06:49" passed="1" failed="17" warnings="9" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>