<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="QuickTest Professional" productVer="11.00" os="Windows 7" host="PC183615"><DocLocation><![CDATA[D:\Soft\TetrisProject\TetrisProject\Slingshot\src\bg\framework\app\functional\util\qtpScripts\SubmitMeterRead]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[SubmitMeterRead]]></DName>
<Res><![CDATA[Res10]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Session]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiSession]]></Details>
<Time><![CDATA[11/14/2013 - 11:57:16]]></Time>
<TimeTick>1384410436</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[wndSAPEasyAccess]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[11/14/2013 - 11:57:16]]></Time>
<TimeTick>1384410436</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[wndSAPEasyAccess.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/14/2013 - 11:57:16]]></Time>
<TimeTick>1384410436</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="10" Source="Action1" SourceLine="31" >
<Disp><![CDATA[wndSAPEasyAccess.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA["OKCode":Set "/n ECENV_BP"]]></Obj>
<Details plainTxt="False" ><![CDATA[Set "/n ECENV_BP"]]></Details>
<Time><![CDATA[11/14/2013 - 11:57:16]]></Time>
<TimeTick>1384410436</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="12" Source="Action1" SourceLine="34" >
<Disp><![CDATA["OKCode":Set "/n ECENV_BP"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[SendKey ENTER]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey ENTER]]></Details>
<Time><![CDATA[11/14/2013 - 11:57:16]]></Time>
<TimeTick>1384410436</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="14" Source="Action1" SourceLine="35" >
<Disp><![CDATA[SendKey ENTER]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="9" Source="Action1" SourceLine="31" >
<Disp><![CDATA[wndSAPEasyAccess]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[wndDataEnvironmentBusiness]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[11/14/2013 - 11:57:19]]></Time>
<TimeTick>1384410439</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[wndDataEnvironmentBusiness.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/14/2013 - 11:57:19]]></Time>
<TimeTick>1384410439</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="16" Source="Action1" SourceLine="54" >
<Disp><![CDATA[wndDataEnvironmentBusiness.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA["edtBusiness Partner":Set "2000022622"]]></Obj>
<Details plainTxt="False" ><![CDATA[Set "2000022622"]]></Details>
<Time><![CDATA[11/14/2013 - 11:57:19]]></Time>
<TimeTick>1384410439</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" Source="Action1" SourceLine="37" >
<Disp><![CDATA["edtBusiness Partner":Set "2000022622"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[SendKey ENTER]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey ENTER]]></Details>
<Time><![CDATA[11/14/2013 - 11:57:19]]></Time>
<TimeTick>1384410439</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="20" Source="Action1" SourceLine="38" >
<Disp><![CDATA[SendKey ENTER]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="15" Source="Action1" SourceLine="54" >
<Disp><![CDATA[wndDataEnvironmentBusiness]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[wndDataEnvironment]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[11/14/2013 - 11:57:19]]></Time>
<TimeTick>1384410439</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[wndDataEnvironment.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/14/2013 - 11:57:19]]></Time>
<TimeTick>1384410439</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="22" Source="Action1" SourceLine="40" >
<Disp><![CDATA[wndDataEnvironment.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="21" Source="Action1" SourceLine="40" >
<Disp><![CDATA[wndDataEnvironment]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[wndDataEnvironment_2]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[11/14/2013 - 11:57:19]]></Time>
<TimeTick>1384410439</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA["Collapse subtree   (Ctrl+Shift":Click]]></Obj>
<Details plainTxt="False" ><![CDATA[Click]]></Details>
<Time><![CDATA[11/14/2013 - 11:57:19]]></Time>
<TimeTick>1384410439</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="25" Source="Action1" SourceLine="214" >
<Disp><![CDATA["Collapse subtree   (Ctrl+Shift":Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="24" Source="Action1" SourceLine="214" >
<Disp><![CDATA[wndDataEnvironment_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[wndDataEnvironment]]></Obj>
<Details plainTxt="False" ><![CDATA[SAPGuiWindow]]></Details>
<Time><![CDATA[11/14/2013 - 11:57:26]]></Time>
<TimeTick>1384410446</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ SAPGuiLabel ]]]></Obj>
<Details plainTxt="False" ><![CDATA[The "[ SAPGuiLabel ]" object's description matches more than one of the objects currently displayed in your application. Add additional properties to the object description in order to uniquely identify the object.]]></Details>
<Time><![CDATA[11/14/2013 - 11:57:26]]></Time>
<TimeTick>1384410446</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ SAPGuiLabel ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>content = <br>]]></Details>
<Time><![CDATA[11/14/2013 - 11:57:26]]></Time>
<TimeTick>1384410446</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="29" status="Warning" nType="Description" Source="Action1" SourceLine="226" >
<Disp><![CDATA[[ SAPGuiLabel ]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="28" status="Failed" nType="Run Error" Source="Action1" SourceLine="226" >
<Disp><![CDATA[[ SAPGuiLabel ]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="27" status="Failed" Source="Action1" SourceLine="226" >
<Disp><![CDATA[wndDataEnvironment]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="8" status="Failed" Source="Action1" SourceLine="31" >
<Disp><![CDATA[Session]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The &quot;[ SAPGuiLabel ]&quot; object's description matches more than one of the objects currently displayed in your application. Add additional properties to the object description in order to uniquely identify the object.<BR>Line (227): &quot;SAPGuiSession(&quot;Session&quot;).SAPGuiWindow(&quot;wndDataEnvironment&quot;).SAPGuiLabel(&quot;content:=&quot;&amp;conditionContractno).Setfocus&quot;. ]]></Details>
<Time><![CDATA[11/14/2013 - 11:57:26]]></Time>
<TimeTick>1384410446</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="30" status="Failed" Source="Action1" SourceLine="226" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[11/14/2013 - 11:58:27]]></Time>
<TimeTick>1384410507</TimeTick>
<NodeArgs eType="General" icon="12" nRep="31" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/14/2013 - 11:57:12" eTime="11/14/2013 - 11:58:27" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[SubmitMeterRead Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[11/14/2013 - 11:58:28]]></Time>
<TimeTick>1384410508</TimeTick>
<NodeArgs eType="General" icon="13" nRep="34" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/14/2013 - 11:57:11" eTime="11/14/2013 - 11:58:28" passed="0" failed="2" warnings="1" stopped="True" ><Param ><ParamName><![CDATA[BpOrgNumber]]></ParamName><ParamVal><![CDATA[]]></ParamVal>
</Param>
<Param ><ParamName><![CDATA[Accountnumber]]></ParamName><ParamVal><![CDATA[]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test SubmitMeterRead Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>